"""Modular database layer; re-exports public API."""

from shop_bot.data_manager.db.connection import (
    DB_FILE,
    get_msk_time,
    _now_str,
    _to_datetime_str,
    _normalize_email,
    _normalize_key_row,
    normalize_host_name,
    get_db_connection,
    DbExecResult,
    _exec,
    _fetch_row,
    _fetch_list,
    _fetch_val,
    _check_rowcount,
    _exec_with_check,
    _get_count_stat,
)

from shop_bot.data_manager.db.schema import (
    _get_table_columns,
    _ensure_table_column,
    _ensure_unique_index,
    _ensure_index,
    initialize_db,
    _ensure_default_values,
    _ensure_users_columns,
    _ensure_hosts_columns,
    _ensure_device_tiers_table,
    _ensure_plans_columns,
    _ensure_support_tickets_columns,
    _finalize_vpn_key_indexes,
    _rebuild_vpn_keys_table,
    _ensure_vpn_keys_schema,
    _ensure_webapp_settings_table,
    run_migration,
    _ensure_pending_transactions_table,
    _ensure_default_button_configs,
    _ensure_ssh_targets_table,
    _ensure_gift_tokens_table,
    _ensure_seller_users_table,
    _ensure_promo_tables,
    _ensure_host_speedtests_table,
    _ensure_resource_metrics_table,
    _ensure_broadcast_history_tables,
)

from shop_bot.data_manager.db.metrics import (
    insert_resource_metric,
    get_latest_resource_metric,
    get_resource_metrics,
    get_metrics_series,
)

from shop_bot.data_manager.db.hosts import (
    create_host,
    update_host_subscription_url,
    update_host_description,
    update_host_traffic_settings,
    update_host_url,
    update_host_remnawave_settings,
    update_host_ssh_settings,
    update_host_name,
    delete_host,
    get_host,
    toggle_host_visibility,
    get_device_tiers,
    add_device_tier,
    update_device_tier,
    delete_device_tier,
    get_device_tier_by_id,
    update_host_device_mode,
    get_all_hosts,
    get_speedtests,
    get_latest_speedtest,
    insert_host_speedtest,
    get_all_ssh_targets,
    get_ssh_target,
    create_ssh_target,
    update_ssh_target_fields,
    delete_ssh_target,
    rename_ssh_target,
    get_admin_stats,
    create_plan,
    get_plans_for_host,
    get_plan_by_id,
    delete_plan,
    update_plan,
    update_host_button_style,
    update_ssh_target_scheduler,
    update_host_sort_order,
    update_ssh_target_sort_order,
)

from shop_bot.data_manager.db.sellers import (
    add_seller_user,
    get_seller_user,
    delete_seller_user,
)

from shop_bot.data_manager.db.settings import (
    get_setting,
    get_admin_ids,
    is_admin,
    get_all_settings,
    update_setting,
    get_other_value,
    set_other_value,
    get_other_setting,
    update_other_setting,
    get_all_other_settings,
    get_webapp_settings,
    update_webapp_settings,
    increment_webapp_design_stat,
)

from shop_bot.data_manager.db.buttons import (
    get_button_configs,
    get_button_config,
    create_button_config,
    update_button_config,
    reorder_button_configs,
    update_existing_my_keys_button,
    delete_button_config,
)

from shop_bot.data_manager.db.transactions import (
    create_payload_pending,
    _get_pending_metadata,
    get_pending_metadata,
    get_pending_status,
    _complete_pending,
    find_and_complete_pending_transaction,
    get_latest_pending_for_user,
    get_transaction,
    get_total_spent_sum,
    get_total_spent_by_method,
    get_today_income_by_currency,
    create_pending_transaction,
    log_transaction_simple,
    find_and_complete_ton_transaction,
    log_transaction,
    check_transaction_exists,
    get_paginated_transactions,
    get_recent_transactions,
)

from shop_bot.data_manager.db.users import (
    delete_user,
    get_user_id_by_gift_token,
    set_referral_start_bonus_received,
    get_referrals_for_user,
    register_user_if_not_exists,
    add_to_referral_balance,
    set_referral_balance,
    set_referral_balance_all,
    add_to_referral_balance_all,
    get_referral_balance_all,
    get_referral_balance,
    get_balance,
    adjust_user_balance,
    set_balance,
    add_to_balance,
    deduct_from_balance,
    deduct_from_referral_balance,
    get_referral_count,
    get_user,
    get_user_by_email,
    create_user_by_email,
    update_user_password,
    verify_user_email_password,
    link_telegram_to_email_user,
    set_terms_agreed,
    update_user_stats,
    get_user_count,
    set_trial_used,
    get_daily_stats_for_charts,
    get_all_users,
    get_users_paginated,
    get_users_filter_counts,
    toggle_user_pin,
    get_keys_counts_for_users,
    ban_user,
    unban_user,
    delete_user_keys,
    purge_user_account,
    update_user_auth_token,
    _auth_token_is_valid,
    get_user_by_auth_token,
    get_auth_token_by_user_id,
    get_dashboard_user_groups,
)

from shop_bot.data_manager.db.keys import (
    delete_key_by_id,
    update_key_comment,
    get_all_keys,
    get_keys_for_user,
    update_key_email,
    update_key_host,
    create_gift_key,
    get_total_keys_count,
    add_new_key,
    _apply_key_updates,
    update_key_fields,
    delete_key_by_email,
    get_user_keys,
    get_key_by_id,
    get_key_by_email,
    get_key_by_remnawave_uuid,
    update_key_info,
    update_key_host_and_info,
    get_next_key_number,
    get_keys_for_host,
    get_all_vpn_users,
    update_key_status_from_server,
)

from shop_bot.data_manager.db.support import (
    create_support_ticket,
    get_or_create_open_ticket,
    add_support_message,
    update_ticket_thread_info,
    get_ticket,
    get_ticket_by_thread,
    get_user_tickets,
    get_ticket_messages,
    set_ticket_status,
    update_ticket_subject,
    delete_ticket,
    get_tickets_paginated,
    get_open_tickets_count,
    get_waiting_tickets_count,
    get_support_badge_counts,
    get_closed_tickets_count,
    get_all_tickets_count,
    get_important_tickets_count,
    get_support_inbox_stats,
    get_tickets_for_export,
    toggle_ticket_important,
    can_reopen_support_ticket,
    get_ticket_reopen_deadline,
)

__all__ = ['DB_FILE', 'get_msk_time', '_now_str', '_to_datetime_str', '_normalize_email', '_normalize_key_row', 'normalize_host_name', 'get_db_connection', 'DbExecResult', '_exec', '_fetch_row', '_fetch_list', '_fetch_val', '_check_rowcount', '_exec_with_check', '_get_count_stat', '_get_table_columns', '_ensure_table_column', '_ensure_unique_index', '_ensure_index', 'initialize_db', '_ensure_default_values', '_ensure_users_columns', '_ensure_hosts_columns', '_ensure_device_tiers_table', '_ensure_plans_columns', '_ensure_support_tickets_columns', '_finalize_vpn_key_indexes', '_rebuild_vpn_keys_table', '_ensure_vpn_keys_schema', '_ensure_webapp_settings_table', 'run_migration', '_ensure_pending_transactions_table', '_ensure_default_button_configs', '_ensure_ssh_targets_table', '_ensure_gift_tokens_table', '_ensure_seller_users_table', '_ensure_promo_tables', '_ensure_host_speedtests_table', '_ensure_resource_metrics_table', 'insert_resource_metric', 'get_latest_resource_metric', 'get_resource_metrics', 'get_metrics_series', 'create_host', 'update_host_subscription_url', 'update_host_description', 'update_host_traffic_settings', 'update_host_url', 'update_host_remnawave_settings', 'update_host_ssh_settings', 'update_host_name', 'delete_host', 'get_host', 'toggle_host_visibility', 'get_device_tiers', 'add_device_tier', 'update_device_tier', 'delete_device_tier', 'get_device_tier_by_id', 'update_host_device_mode', 'get_all_hosts', 'get_speedtests', 'get_latest_speedtest', 'insert_host_speedtest', 'get_all_ssh_targets', 'get_ssh_target', 'create_ssh_target', 'update_ssh_target_fields', 'delete_ssh_target', 'rename_ssh_target', 'get_admin_stats', 'create_plan', 'get_plans_for_host', 'get_plan_by_id', 'delete_plan', 'update_plan', 'update_host_button_style', 'update_ssh_target_scheduler', 'update_host_sort_order', 'update_ssh_target_sort_order', 'add_seller_user', 'get_seller_user', 'delete_seller_user', 'get_setting', 'get_admin_ids', 'is_admin', 'get_all_settings', 'update_setting', 'get_other_value', 'set_other_value', 'get_other_setting', 'update_other_setting', 'get_all_other_settings', 'get_webapp_settings', 'update_webapp_settings', 'increment_webapp_design_stat', 'get_button_configs', 'get_button_config', 'create_button_config', 'update_button_config', 'reorder_button_configs', 'update_existing_my_keys_button', 'delete_button_config', 'create_payload_pending', '_get_pending_metadata', 'get_pending_metadata', 'get_pending_status', '_complete_pending', 'find_and_complete_pending_transaction', 'get_latest_pending_for_user', 'get_transaction', 'get_total_spent_sum', 'get_total_spent_by_method', 'get_today_income_by_currency', 'create_pending_transaction', 'log_transaction_simple', 'find_and_complete_ton_transaction', 'log_transaction', 'check_transaction_exists', 'get_paginated_transactions', 'get_recent_transactions', 'delete_user', 'get_user_id_by_gift_token', 'set_referral_start_bonus_received', 'get_referrals_for_user', 'register_user_if_not_exists', 'add_to_referral_balance', 'set_referral_balance', 'set_referral_balance_all', 'add_to_referral_balance_all', 'get_referral_balance_all', 'get_referral_balance', 'get_balance', 'adjust_user_balance', 'set_balance', 'add_to_balance', 'deduct_from_balance', 'deduct_from_referral_balance', 'get_referral_count', 'get_user', 'get_user_by_email', 'create_user_by_email', 'update_user_password', 'verify_user_email_password', 'link_telegram_to_email_user', 'set_terms_agreed', 'update_user_stats', 'get_user_count', 'set_trial_used', 'get_daily_stats_for_charts', 'get_all_users', 'get_users_paginated', 'get_users_filter_counts', 'toggle_user_pin', 'get_keys_counts_for_users', 'ban_user', 'unban_user', 'delete_user_keys', 'purge_user_account', 'update_user_auth_token', '_auth_token_is_valid', 'get_user_by_auth_token', 'get_auth_token_by_user_id', 'get_dashboard_user_groups', 'delete_key_by_id', 'update_key_comment', 'get_all_keys', 'get_keys_for_user', 'update_key_email', 'update_key_host', 'create_gift_key', 'get_total_keys_count', 'add_new_key', '_apply_key_updates', 'update_key_fields', 'delete_key_by_email', 'get_user_keys', 'get_key_by_id', 'get_key_by_email', 'get_key_by_remnawave_uuid', 'update_key_info', 'update_key_host_and_info', 'get_next_key_number', 'get_keys_for_host', 'get_all_vpn_users', 'update_key_status_from_server', 'create_support_ticket', 'get_or_create_open_ticket', 'add_support_message', 'update_ticket_thread_info', 'get_ticket', 'get_ticket_by_thread', 'get_user_tickets', 'get_ticket_messages', 'set_ticket_status', 'update_ticket_subject', 'delete_ticket', 'get_tickets_paginated', 'get_open_tickets_count', 'get_waiting_tickets_count', 'get_support_badge_counts', 'get_closed_tickets_count', 'get_all_tickets_count', 'get_important_tickets_count', 'get_support_inbox_stats', 'get_tickets_for_export', 'toggle_ticket_important', 'can_reopen_support_ticket', 'get_ticket_reopen_deadline']
